<div>
    <div>
        <div>
            <table>
                <thead>
                    <tr>
                        <th>prato_principal</th>
                        <th>vegetariana</th>
                        <th>vegana</th>
                        <th>guarnição</th>
                        <th>arroz</th>
                        <th>feijao</th>
                        <th>salada1</th>
                        <th>salada2</th>
                        <th>salada3</th>
                        <th>salada4</th>
                        <th>sobremesa</th>
                        <th>data</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($cardapios as $cardapio)
                        <tr>
                            <td>{{$cardapio->prato_principal}}</td>
                            <td>{{$cardapio->vegetariana}}</td>
                            <td>{{$cardapio->vegana}}</td>
                            <td>{{$cardapio->guarnicao}}</td>
                            <td>{{$cardapio->arroz}}</td>
                            <td>{{$cardapio->feijao}}</td>
                            <td>{{$cardapio->salada1}}</td>
                            <td>{{$cardapio->salada2}}</td>
                            <td>{{$cardapio->salada3}}</td>
                            <td>{{$cardapio->salada4}}</td>
                            <td>{{$cardapio->sobremesa}}</td>
                            <td>{{$cardapio->data}}</td>
                        </th>
                    @endforeach
                </tbody>
            </table>
        </div>
</div>
