<div>
    <div>
        <div>
            <table border="1">
                <thead>
                    <tr>
                        <th>Prato Principal</th>
                        <th>vegetariana</th>
                        <th>vegana</th>
                        <th>Guarnição</th>
                        <th>arroz</th>
                        <th>feijao</th>
                        <th>salada1</th>
                        <th>salada2</th>
                        <th>salada3</th>
                        <th>salada4</th>
                        <th>sobremesa</th>
                        <th>data</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($cardapios as $cardapio)
                        <tr>
                            <td>{{$cardapios->pratoPrincipal}}</td>
                            <td>{{$cardapios->vegetariana}}</td>
                            <td>{{$cardapios->vegana}}</td>
                            <td>{{$cardapios->guarnicao}}</td>
                            <td>{{$cardapios->arroz}}</td>
                            <td>{{$cardapios->feijao}}</td>
                            <td>{{$cardapios->salada1}}</td>
                            <td>{{$cardapios->salada2}}</td>
                            <td>{{$cardapios->salada3}}</td>
                            <td>{{$cardapios->salada4}}</td>
                            <td>{{$cardapios->sobremesa}}</td>
                            <td>{{$cardapios->data}}</td>
                        </th>
                    @endforeach
                </tbody>
            </table>
        </div>
</div>
</div>
